### ISSUE TITLE
Image thumbnail

### ISSUE THREAD

**Issue by piotrfilipek** [SaifurRahmanMohsin/magnificgallery-plugin#7]
Hi, how can I implement a mechanism that create a thumbnails? I like this plugin, but when I upload 16:9 images, each one of them is too wide. Also when I set dimensions to 200x200px each image is resized, but without proporions.

**Comment by mohsin** [comment]
You will have to override the partial and change the thumb function to suit your need. In the CMS tab, simply hold Cmd and double click on the component code inside the editor (alt or ctrl + double click on windows) and it will expand and expose the partial (or) use the method described [here](http://octobercms.com/docs/cms/components#overriding-partials).

Now in the partial code change the thumb function to your preference of dimensions and image mode:
So for example, you change `image.thumb(width, height)` to `image(width,height,{'mode':'crop’})` or any other mode to fit your proportions.
Other modes incl. auto, exact, portrait and landscape. It’s somewhere in the OctoberCMS documentation. (Search for file attachments)

Let me know if this solves the issue so that I can close it.
